include:
  - board: nice_nano_v2
    shield: zion01_left
    snippet: studio-rpc-webusb
    config: |
      CONFIG_ZMK_STUDIO=y
      CONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano_v2
    shield: zion01_right
